### ISSUE TITLE
Sidebar does not remain shrunk

### ISSUE THREAD

**Issue by lucasitz** [app-generator/django-atlantis-dark#1]
I noticed that when you click on the hamburger menu to shrink the sidebar it shrinks, but when you update the page it doesn't stay shrunk, is there a solution for that?

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
