### ISSUE TITLE
A dropdown does not display properly

### ISSUE THREAD

**Issue by Eli-Pan** [app-generator/django-atlantis-dark#2]
In Forms.html under 'Form Floating Label', the options in second select dropdown does not display properly.
![submit](https://user-images.githubusercontent.com/70869022/94749888-3d329600-03c8-11eb-9b66-63a6af303e08.PNG)

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
